Fat 47439 task1
kndnba/AndroidTask1 pull request #1
Opened 2022-12-15 12:15 UTC by kndnba

2022-12-15 12:28 UTC, daddymercury commented on app/src/main/java/com/bignerdranch/android/androidtask1/MainActivity.kt
> +        Log.d(TAG, "onCreate() called")
Вызов логов тоже нужно убрать

2022-12-15 12:29 UTC, daddymercury commented on app/src/main/java/com/bignerdranch/android/androidtask1/MainActivity.kt
> +private const val TAG = "MainActivity"
добавь TAG  в companion object

2022-12-15 12:30 UTC, daddymercury commented on app/src/main/java/com/bignerdranch/android/androidtask1/MainActivity.kt
> +        }
```suggestion
        binding.topAppBar.let { toolbar->
        drawerLayout = binding.container
        navigationView = binding.navigationView
        navigationView.setNavigationItemSelectedListener(this)
        fragment = Task1Fragment()
        commitFragment()
        toolbar.setOnClickListener{
            drawerLayout.open()
        }
        }
```

2022-12-15 12:31 UTC, daddymercury commented on app/src/main/java/com/bignerdranch/android/androidtask1/MainActivity.kt
> +    }
```suggestion
    
```

2022-12-15 12:31 UTC, daddymercury commented on app/src/main/java/com/bignerdranch/android/androidtask1/adapter/MyAdapter.kt
> +
Лишний отступ

2022-12-15 12:32 UTC, daddymercury commented on app/src/main/java/com/bignerdranch/android/androidtask1/adapter/MyAdapter.kt
> +class MyAdapter(private val names: List<String>, private val context: Context) : RecyclerView.Adapter<MyAdapter.MyViewHolder>(){
```suggestion
class MyAdapter(
private val names: List<String>, 
private val context: Context
) : RecyclerView.Adapter<MyAdapter.MyViewHolder>(){
```

2022-12-15 12:36 UTC, daddymercury commented on app/src/main/java/com/bignerdranch/android/androidtask1/adapter/MyAdapter.kt
> +            }
```suggestion
            myDialogFragment.message = getMessageByPosition(names, position)
            
            
            private fun getMessageByPosition(names: List<String>, position: Int) = when (names[position]){
                 "Квадрат" -> "Первый"
                 "Треугольник" -> "Второй"
                 "Параллелепипед" -> "Третий"
                 "Тетраэдр" -> "Четвертый"
                 "Круг" -> "Пятый"
                 "Трапеция" -> "Шестой"
                 "Куб" -> "Седьмой"
                 "Овал" -> "Восьмой"
                 "Ромб" -> "Девятый"
                 "Окружность" -> "Десятый"
                 else -> {""}
```

2022-12-15 12:36 UTC, daddymercury commented on app/src/main/java/com/bignerdranch/android/androidtask1/task1/BlankFragment.kt
> +private const val TAG = "BlankFragment"
companion object

2022-12-15 12:37 UTC, daddymercury commented on app/src/main/java/com/bignerdranch/android/androidtask1/task1/BlankFragment.kt
> +    }
```suggestion
```

2022-12-15 12:37 UTC, daddymercury commented on app/src/main/java/com/bignerdranch/android/androidtask1/task1/BlankFragment.kt
> +        Log.d(TAG, "onCreateView() called")
они убрать

2022-12-15 12:38 UTC, daddymercury commented on app/src/main/java/com/bignerdranch/android/androidtask1/task1/BlankFragment.kt
> +    }
```suggestion
```

2022-12-15 12:38 UTC, daddymercury commented on app/src/main/java/com/bignerdranch/android/androidtask1/task1/BlankFragment.kt
> +    }
Такая же функция есть в уже в библиотеке самого Колтуна это убери и воспользуйся стандартной

2022-12-15 12:41 UTC, daddymercury commented on app/src/main/java/com/bignerdranch/android/androidtask1/task1/DialogFragment.kt
> +
лишний отступ

2022-12-15 12:41 UTC, daddymercury commented on app/src/main/java/com/bignerdranch/android/androidtask1/task1/RecyclerViewFragment.kt
> +    override fun onAttach(context: Context) {
тоже убери плз методы жизненного цикла

2022-12-15 12:45 UTC, daddymercury commented on app/src/main/res/layout/fragment_blank.xml
> +            android:id="@+id/textView"
textView - замени на что-то чтобы отображало суть этого текст вью

2022-12-15 12:46 UTC, daddymercury commented on app/src/main/res/layout/fragment_task1.xml
> +        android:layout_height="650dp"
нужно убрать хард код "650dp"

2022-12-15 12:46 UTC, daddymercury commented on app/src/main/res/layout/fragment_task1.xml
> +        app:layout_constraintHorizontal_bias="0.515"
layout_constraintHorizontal_bias - тоже убрать

2022-12-15 12:46 UTC, daddymercury commented on app/src/main/res/layout/fragment_task1.xml
> +        android:layout_marginBottom="48dp"
можно добавить в dimen значение 48dp и использовать здесь

2022-12-15 12:46 UTC, daddymercury commented on app/src/main/res/layout/fragment_blank.xml
> +            android:layout_weight="4"
убрать веса

2022-12-15 12:47 UTC, daddymercury commented on app/src/main/res/layout/fragment_blank.xml
> +            android:id="@+id/textView2"
поправить айди

2022-12-15 12:47 UTC, daddymercury commented on app/src/main/res/layout/fragment_blank.xml
> +            android:layout_weight="4"
вес убрать

2022-12-15 12:47 UTC, daddymercury commented on app/src/main/res/layout/fragment_task2.xml
> +        android:text="Hello task 2 fragment"
использовать с ресурсов строку

2022-12-15 12:48 UTC, daddymercury commented on app/src/main/res/layout/fragment_task2.xml
> +        app:layout_constraintTop_toTopOf="@+id/task2_container" />
```suggestion
        здесь и везде где ты обращаешься к айдишкам убрать плюсы
        app:layout_constraintBottom_toBottomOf="@id/task2_container"
        app:layout_constraintEnd_toEndOf="@id/task2_container"
        app:layout_constraintStart_toStartOf="@id/task2_container"
        app:layout_constraintTop_toTopOf="@id/task2_container" />
```

2022-12-15 12:48 UTC, daddymercury commented on app/src/main/res/layout/fragment_task2.xml
> +        android:layout_height="650dp"
убрать хард код 650 и биас

2022-12-15 12:49 UTC, daddymercury commented on app/src/main/res/layout/fragment_task3.xml
> +        android:text="Hello task 3 fragment"
текст в ресурсы и убрать +

2022-12-15 12:49 UTC, daddymercury commented on app/src/main/res/layout/fragment_task3.xml
> +        app:layout_constraintHorizontal_bias="0.515"
тож самое с харкодом и биас

2022-12-15 12:49 UTC, daddymercury commented on app/src/main/res/layout/item_layout.xml
> +
хардкор и дищняя строка

2022-12-15 12:50 UTC, daddymercury commented on app/src/main/res/layout/item_layout.xml
> +    app:cardElevation="8dp"
добавил 8 в дименс

2022-12-15 12:50 UTC, daddymercury commented on app/src/main/res/layout/item_layout.xml
> +            android:text="name"
в ресурсы

2022-12-15 12:51 UTC, daddymercury requested changes
Хорошая работа

2022-12-19 08:04 UTC, kndnba commented
done (probably)

2022-12-19 10:41 UTC, merged